### ISSUE TITLE
Implementations of std::ops traits (Add/Sub/etc)

### ISSUE THREAD

**Issue by comp500** [Adel-ak/currency_rs#2]
**Is your feature request related to a problem? Please describe.**
When dealing with currency in Rust code, it's often necessary to do operations (e.g. adding/subtracting) on multiple parsed values.

**Describe the solution you'd like**
Implement the traits from [`std::ops`](https://doc.rust-lang.org/std/ops/index.html) that make sense to use with `Currency`, in particular `Add`, `AddAssign`, `Sub`, `SubAssign`, `Mul` and `MulAssign` (`Div` might be more tricky due to remainder issues).

This allows `Currency` values to be added using the built-in operators, e.g. `Currency::new_float(2.51, None) + Currency::new_float(2.51, None)`.

**Describe alternatives you've considered**
The built-in `add` / `subtract` / `multiply` / `divide` functions can be used to do operations with `f64` values, but if the values are already parsed as `Currency` they would need to be converted back to `f64` first.

**Comment by Ryiski** [comment]
@comp500 that is a great idea, I'll have a look at it as soon as I can

**Comment by Ryiski** [comment]
Commit 5f155c6 implementations the std::ops traits...
