### ISSUE TITLE
`set_precision` doesn't remove 0s, so `set_from_cents` + `set_precision(0)` does not format correctly

### ISSUE THREAD

**Issue by Gremious** [Adel-ak/currency_rs#3]
I pass a format function the value in cents, or more accurately, in hundreds since e.g. JPY don't _really_ do subunits.
But I have to deal with multiple currencies, so I do:

```
let value = 100.0;

let otp = CurrencyOpts::new()
	.set_from_cents(true) // The data I have is in centi units, so, from cents is true
	.set_precision(0) // Japanese yen aren't actually fractional
	.set_symbol("¥");

Currency::new_float(value, Some(otp))
```

The expected outcome is that because of `set_from_cents` is true, this will calculate that I have 1 yen, and then because precision is at 0, it will display `¥1` rather than `¥1.00`.

Instead, it still displays the latter, but without the dot - e.g. `¥100`.
If I set precision to 1, it displays `¥10.0` which is also incorrect, it should be `¥1.0`

Either `set_from_cents` does not calculate the value to correctly be `1.00` or `set_precision` does not format the currencty correctly, or both.

**Comment by Ryiski** [comment]
@Gremious Sorry for the late response.

I am not sure as to what the issue is, it seems to me that this feature works as intended.

That's true, if your input is `let value = 1.0;` and you have `set_from_cents` as true and `set_precision` as 0, so your out put should be `¥1` (one yen), it will not display as `¥1.00` cause set_precision is 0,

Now since your input is `let value = 100.0;` with the same options set, your out put will be `¥100` (one hundred yen) with 0 precision

Am i missing something here.

Again sorry for the late response, been busy at life 🙇🏾‍♂️.

**Comment by Gremious** [comment]
> let value = 1.0; and you have `set_from_cents` [...] so your out put should be ¥1 (one yen)

If it's from cents, should it not be 0.01? 

Same with `let value = 100.0;` - 100 cents should be 1 dollar/yen/etc.?

**Comment by Ryiski** [comment]
I think there is a confusion here.

First of all, since the japanese currency has no fraction, you don't need to use `set_from_cents`.

```
Same with let value = 100.0; - 100 cents should be 1 dollar/yen/etc.?
```
Yes: if its dollar and precision is set to 2 because USD has 2 decimal points.
No: for yen if precision is set to 0.

`set_from_cents` is intended for countries with fraction currency like USD, which has 2 decimal points.

So if you want to convert cents to dollar you use `set_from_cents` and set the right precision for the given currency

Examples


The country i am in (KUWAIT) has 3 decimal points, so 1000 fils (<- cents) = 1 dinar (<- dollars). 

```rs
use currency_rs::{Currency, CurrencyOpts};

fn usd_from_cents(value: f64) -> Currency {
    let otp = CurrencyOpts::new()
        .set_from_cents(true)
        .set_precision(2)
        .set_symbol("$ ");

    Currency::new_float(value, Some(otp))
}

fn usd(value: f64) -> Currency {
    let otp = CurrencyOpts::new().set_precision(2).set_symbol("$ ");

    Currency::new_float(value, Some(otp))
}

fn yen(value: f64) -> Currency {
    let otp = CurrencyOpts::new().set_precision(0).set_symbol("¥ ");

    Currency::new_float(value, Some(otp))
}

fn yen_from_cents(value: f64) -> Currency {
    let otp = CurrencyOpts::new()
        .set_from_cents(true) // <- Not really needed cause, japan has no cents in a way
        .set_precision(0)
        .set_symbol("¥ ");

    Currency::new_float(value, Some(otp))
}

fn kwd_from_cents(value: f64) -> Currency {
    let otp = CurrencyOpts::new()
        .set_from_cents(true)
        .set_precision(3)
        .set_symbol("KWD ");

    Currency::new_float(value, Some(otp))
}

fn kwd(value: f64) -> Currency {
    let otp = CurrencyOpts::new()
        .set_precision(3)
        .set_symbol("KWD ");

    Currency::new_float(value, Some(otp))
}

fn main() {
    let usd_from_cents1 = usd_from_cents(100.0);
    let usd_from_cents2 = usd_from_cents(99.0);

    println!("\nusd from cents");
    println!("{}", usd_from_cents1.format()); // output -> $ 1.00
    println!("{}", usd_from_cents2.format()); // output -> $ 0.99

    let usd1 = usd(1.0);
    let usd2 = usd(0.99);

    println!("\nusd");
    println!("{}", usd1.format()); // output -> $ 1.00
    println!("{}", usd2.format()); // output -> $ 0.99

    let yen1 = yen(100.0);
    let yen2 = yen(99.0);

    println!("\nyen");
    println!("{}", yen1.format()); // output -> ¥ 100
    println!("{}", yen2.format()); // output -> ¥ 99

    let yen_from_cents1 = yen_from_cents(100.0);
    let yen_from_cents2 = yen_from_cents(99.0);

    println!("\nyen from cents");
    println!("{}", yen_from_cents1.format()); // output -> ¥ 100
    println!("{}", yen_from_cents2.format()); // output -> ¥ 99

    let kwd_from_cents1 = kwd_from_cents(1000.0);
    let kwd_from_cents2 = kwd_from_cents(990.0);

    println!("\nkuwait from cents");
    println!("{}", kwd_from_cents1.format()); // output -> KWD 1.000
    println!("{}", kwd_from_cents2.format()); // output -> KWD 0.990

    let kwd1 = kwd(1.0);
    let kwd2 = kwd(0.99);

    println!("\nkuwait");
    println!("{}", kwd1.format()); // output -> KWD 1.000
    println!("{}", kwd2.format()); // output -> KWD 0.990
}

```

**Comment by Gremious** [comment]
Ah, I think I understand now, `from_cents` actually accounts for `precision`, so that you can do the amount of "cents" the currency expects (e.g. 1000), and it will render it right.

My data happens to be standardized so `100.0 = 1 dollar/yen/kwd/any` (It's what YouTube gives you) so I though `yen(100.0)` would return `¥ 100` while `yen_from_cents(100.0)` would do `¥ 1`
But if it worked like that, you couldn't do `kwd_from_cents(1000.0)` as one would expect.

For my case then, what I do right now both works and looks like the intended way:

```rust
// e.g. 10.00 for ¥10, yen will never be give you 10.25 since yen doesn't really have cents
// dollar might
let value = value as f64 / 100.;

let otp = CurrencyOpts::new()
	.set_from_cents(false)
	// 0 for yen, 2 for dollar, etc.
	.set_precision(...)
```

Thank you, you can close this issue :)
